apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gse-apply-manifests-pvc-task
spec:
  params:
    - default: 'k8s'
      name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/cos-liberty-tekton/cos-liberty'
      name: docker-image
      type: string
    - default: 'http://github.com/ibm-cloud-architecture/appmod-liberty-tekton'   
      name: git-url
      type: string
  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          set -e
          SHORT_GIT_HASH=$(cat .git/FETCH_HEAD | awk '{print substr($1,0,7)}')
          NEW_IMAGE=$(params.docker-image):$SHORT_GIT_HASH
          echo Setting image to $NEW_IMAGE
          echo -----------------------------------
          echo Updaing manifests in $(inputs.params.manifest_dir) directory
          sed -i "s|<DOCKER_IMAGE>|${NEW_IMAGE}|g" ./$(params.manifest_dir)/deployment.yaml
          echo -----------------------------------
          echo Applying manifests in $(params.manifest_dir) directory
          oc apply -f $(params.manifest_dir)
          echo -----------------------------------
