#kind: Route
#apiVersion: route.openshift.io/v1
#metadata:
#  name: cos-liberty-9081
#  namespace: pipelines-tutorial
#  labels:
#    application: cos-liberty
#spec:
#  to:
#    kind: Service
#    name: cos-liberty
#    weight: 100
#  port:
#    targetPort: http
#  tls:
#    termination: passthrough
#  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cos-liberty-9080
  namespace: pipelines-tutorial
  annotations:
    description: "Route for application http service /CustomerOrderServicesWeb username: rbarcia and password: bl0wfish"
  labels:
    application: cos-liberty
spec:
  to:
    name: cos-liberty
  port:
    targetPort: 9080-tcp
  tls:
    termination: edge
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cos-liberty-9081
  namespace: pipelines-tutorial
  labels:
    application: cos-liberty
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: cos-liberty
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
